FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@11.7.0 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_CLIENT_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_CLIENT_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_CLIENT_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_CLIENT_API_KEY
ARG NEXT_PUBLIC_FIREBASE_CLIENT_APP_ID
ARG NEXT_PUBLIC_FIREBASE_CLIENT_MEASUREMENT_ID
ARG NEXT_PUBLIC_AUTH_BACKEND
ARG NEXT_PUBLIC_IAF_JAF_BACKEND
ARG NEXT_PUBLIC_EXAM_BACKEND
ARG NEXT_PUBLIC_OPPORTUNITY_BACKEND
ARG NEXT_PUBLIC_RESUME_BACKEND

ENV NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_CLIENT_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_CLIENT_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_CLIENT_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_CLIENT_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_CLIENT_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_CLIENT_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_CLIENT_API_KEY=$NEXT_PUBLIC_FIREBASE_CLIENT_API_KEY
ENV NEXT_PUBLIC_FIREBASE_CLIENT_APP_ID=$NEXT_PUBLIC_FIREBASE_CLIENT_APP_ID
ENV NEXT_PUBLIC_FIREBASE_CLIENT_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_CLIENT_MEASUREMENT_ID
ENV NEXT_PUBLIC_AUTH_BACKEND=$NEXT_PUBLIC_AUTH_BACKEND
ENV NEXT_PUBLIC_IAF_JAF_BACKEND=$NEXT_PUBLIC_IAF_JAF_BACKEND
ENV NEXT_PUBLIC_EXAM_BACKEND=$NEXT_PUBLIC_EXAM_BACKEND
ENV NEXT_PUBLIC_OPPORTUNITY_BACKEND=$NEXT_PUBLIC_OPPORTUNITY_BACKEND
ENV NEXT_PUBLIC_RESUME_BACKEND=$NEXT_PUBLIC_RESUME_BACKEND

RUN pnpm build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 8080
CMD ["node", "server.js"]